In [32]:
import numpy as np 

##Data Types & Attributes

In [34]:
#Que = 1
arr = np.arange(6) 
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int32


In [37]:
#Que = 2
arr = np.array([1.0, 2.0, 3.0])
if arr.dtype == np.float64:
    print("The array data type is float64.")
else:
    print("The array data type is not float64.")

The array data type is float64.


In [38]:
#Que = 3
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Complex Array:", arr)
print("Data type:", arr.dtype)

Complex Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [236]:
# Que = 4
int_arr = np.array([1, 2, 3, 4])
float_arr = int_arr.astype(np.float32)
print("Convert into float32:", float_arr)
print("Data type:", float_arr.dtype)

Convert into float32: [1. 2. 3. 4.]
Data type: float32


In [40]:
#Que = 5
float64_arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
float32_arr = float64_arr.astype(np.float32)
print("Converted to float32:", float32_arr)
print("Original dtype:", float64_arr.dtype)
print("New dtype:", float32_arr.dtype)

Converted to float32: [1.1234568 2.9876542]
Original dtype: float64
New dtype: float32


In [43]:
#Que = 6
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
a = np.array([[1, 2], [3, 4]])
print("Attributes:", array_attributes(a))

Attributes: ((2, 2), 4, dtype('int32'))


In [44]:
#Que = 7
def array_dimension(arr):
    return arr.ndim
b = np.array([[[1, 2], [3, 4]]])
print("Dimensions:", array_dimension(b))

Dimensions: 3


In [46]:
#Que = 8
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
c = np.array([1, 2, 3], dtype=np.int32)
print("Item size and total size:", item_size_info(c))

Item size and total size: (4, 12)


In [47]:
# Que = 9
def array_strides(arr):
    return arr.strides
d = np.array([[1, 2], [3, 4]])
print("Strides:", array_strides(d))

Strides: (8, 4)


In [51]:
#Que = 10
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


##Array Creation

In [52]:
#Que = 11
def create_zeros_array(n):
    return np.zeros(n)
print("Zeros array:", create_zeros_array(5))

Zeros array: [0. 0. 0. 0. 0.]


In [56]:
#Que = 12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
print("Ones matrix\n:", create_ones_matrix(3, 4))

Ones matrix
: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
#Que = 13
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
print("Ranged array:", generate_range_array(0, 10, 2))

Ranged array: [0 2 4 6 8]


In [58]:
#Que = 14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print("Linear space array:", generate_linear_space(1, 5, 5))

Linear space array: [1. 2. 3. 4. 5.]


In [60]:
#Que = 15
def create_identity_matrix(n):
    return np.identity(n)
print("Identity matrix:\n", create_identity_matrix(4))

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [237]:
#Que = 16
def list_to_numpy_array(py_list):
    return np.array(py_list)
print("Numpy array:", list_to_numpy_array([1, 2, 3, 4]))

Numpy array: [1 2 3 4]


In [65]:
#Que = 17
a = np.array([10, 20, 30, 40])
a1 = a.view()
print("View array:", a1)

View array: [10 20 30 40]


##Concatenation and Stacking

In [68]:
#Que = 18
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
print(concatenate_arrays([1,2,3],[6,7,8]))


[1 2 3 6 7 8]


In [72]:
#Que = 19
def horizontal_concatenate(arr1, arr2):
    return np.concatenate((arr1, arr2), axis=1)
print(horizontal_concatenate([[1,2,3,4]],[[9,7,6,8]])) 

[[1 2 3 4 9 7 6 8]]


In [79]:
#Que = 20
def vertical_stack(arrays):
     return np.vstack(arrays)
print(vertical_stack([1,3,4]))

[[1]
 [3]
 [4]]


##Pandas + NumPy

In [85]:
import numpy as np
import pandas as pd

In [132]:
#Que = 24
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0       18      100       44
1       49       71       26
2       28       36       29
3       74       82       76
4        6       85       86


In [133]:
#Que = 25
def replace_negatives_with_zero(df, a):
    df[a] = np.where(df[a] < 0, 0, df[a])
    return df
data = {
    'A': [10, -5, 7, -2, 15],}
df = pd.DataFrame(data)
df = replace_negatives_with_zero(df, 'A')

print(df)


    A
0  10
1   0
2   7
3   0
4  15


##Array Generation

In [134]:
#Que 21
def generate_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)
arr = generate_range_array(1, 10, 2)
print(arr)


[1 3 5 7 9]


In [139]:
#Que 22
def generate_linear_space():
    return np.linspace(0, 1, 10)
arr = generate_linear_space()
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [140]:
#Que 23
def generate_log_space():
    return np.logspace(0, 3, 5)
arr = generate_log_space()
print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


##Indexing and Slicing

In [143]:
#QUE 26
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2] 
print("3rd element:", third_element)

3rd element: 30


In [144]:
#Que 27
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = array_2d[1, 2] 
print( element)

6


In [146]:
#Que 28
arr = np.array([1, 3, 5, 7, 9])
a = arr[arr > 5]
print(a)

[7 9]


In [147]:
#Que 29
arr = np.array([10, 20, 30, 40, 50, 60, 70])
a = arr[2:6]
print(a)

[30 40 50 60]


In [148]:
#Que 30
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr = a[0:2, 1:3] 
print(arr)

[[2 3]
 [5 6]]


##Advanced Indexing

In [238]:
#Que 31
arr= np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
row_indices = [0, 1, 2]
col_indices = [0, 1, 2]
result = arr[row_indices, col_indices]
print(result)

[10 50 90]


In [154]:
#QUe 32
arr = np.array([5, 8, 12, 3, 7])
threshold = 6
filtered = arr[arr > threshold]
print( threshold, ":", filtered)

6 : [ 8 12  7]


In [155]:
#Que 33
arr_3d = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
i = np.array([0, 1])
j = np.array([1, 0])
k = np.array([1, 0])
result = arr_3d[i, j, k]
print(result)


[4 5]


In [156]:
#Que 34
arr = np.array([10, 15, 20, 25, 30])
result = arr[(arr > 15) & (arr < 30)]
print(result)

[20 25]


In [157]:
#Que 35
array_2d = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])
result = array_2d[row_indices, col_indices]
print("Selected elements:", result)


Selected elements: [30 40 80]


##Broadcasting

In [159]:
#Que 36
arr = np.array([1, 2, 3, 4, 5])
result = arr + 5
print(result)

[ 6  7  8  9 10]


In [161]:
#Que 37
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
factors = np.array([[1], [2], [3]])
result = arr * factors 
print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [162]:
#Que 38
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
to_add = np.array([[10, 20, 30]])  # Shape: (1, 3)
result = arr + to_add
print( result)

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [164]:
#Que 39
a = np.array([[1], [2], [3]])
b = np.array([[10, 20, 30]])  
result = a + b 
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [165]:
#Que 40
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1, 2],[3, 4]])  
try:
    result = a * b  
except ValueError as e:
    print( e)

operands could not be broadcast together with shapes (2,3) (2,2) 


##Aggregations and Statistics

In [166]:
#Que 41
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

col_mean = np.mean(arr, axis=0)
print(col_mean)

[40. 50. 60.]


In [167]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [169]:
#Que 42
row_max = np.max(arr, axis=1)
print(row_max)

[30 60 90]


In [170]:
#Que 43
max_indices = np.argmax(arr, axis=0)
print(max_indices)

[2 2 2]


In [172]:
#Que 45
all_even = np.all(arr % 2 == 0, axis=0)
print(all_even)

[ True  True  True]


##Reshaping and Flattening

In [174]:
#Que 46
arr = np.array([1, 2, 3, 4, 5, 6])
a= arr.reshape(2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [176]:
#Que 47
a = np.array([[1, 2], [3, 4]])
flattened = a.flatten()

print(flattened)

[1 2 3 4]


In [179]:
#Que 48
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
concat_axis0 = np.concatenate((a, b), axis=0)
concat_axis1 = np.concatenate((a, b), axis=1)
print('a',concat_axis0)
print('b',concat_axis1)

a [[1 2]
 [3 4]
 [5 6]
 [7 8]]
b [[1 2 5 6]
 [3 4 7 8]]


In [181]:
#Que 49
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a = np.split(arr, 2, axis=1)
for i in a:
    print(i)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [183]:
#Que 50
arr = np.array([10, 20, 30, 40, 50])
inserted = np.insert(arr, 2, 25)
deleted = np.delete(arr, 3)
print('a',inserted)
print('b',deleted)


a [10 20 25 30 40 50]
b [10 20 30 50]


In [185]:

arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 2, 3, 4])

##Element-wise Operations

In [187]:
#Que 51
a = arr1 + arr2
print(a)

[ 3  6  9 12]


In [188]:
#Que 52
sub = arr1-arr2
print(sub)

[1 2 3 4]


In [189]:
#Que 53
mul = arr1*arr2
print(mul)

[ 2  8 18 32]


In [190]:
#Que 54
div = arr1/arr2
print(div)

[2. 2. 2. 2.]


In [191]:
#Que 55
expo=arr1**arr2
print(expo)

[   2   16  216 4096]


##String Operations

In [192]:
arr = np.array(["Hello World", "Python PROGRAMMING", "HELLO", "data123", "NumPy"])

In [194]:
#Que 56
substring = "o"
counts = np.char.count(arr, substring)
print( counts)

[2 1 0 0 0]


In [198]:
#Que 57
def extract_uppercase(array):
    return np.array([''.join([char for char in s if char.isupper()]) for s in array])
a = extract_uppercase(arr)
print(a)

['HW' 'PPROGRAMMING' 'HELLO' '' 'NP']


In [200]:
#Que 58
replaced = np.char.replace(arr, "Hello", "Hi")
print( replaced)

['Hi World' 'Python PROGRAMMING' 'HELLO' 'data123' 'NumPy']


In [203]:
#Que 59
arr2 = np.array(["!", " is fun", " AGAIN", "_456", " Array"])
concatenated = np.char.add(arr, arr2)
print(concatenated)

['Hello World!' 'Python PROGRAMMING is fun' 'HELLO AGAIN' 'data123_456'
 'NumPy Array']


In [206]:
#Que 56
lengths = np.char.str_len(arr)
max_length = np.max(lengths)
print(max_length)

18


##Descriptive Statistics

In [217]:
#Que 61
arr = np.random.randint(1, 100, 50)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)
print("Mean", mean)
print("Median", median)
print("Variance", variance)
print("Sd", std_dev)


Mean 49.94
Median 55.5
Variance 754.3763999999999
Sd 27.465913420092182


In [218]:
#Que 62
a= np.percentile(arr, 25)
a1 = np.percentile(arr, 75)

print("25th P",a)
print("75th P",a1)


25th P 26.25
75th P 74.5


In [219]:
#Que 63
arr2 = np.random.randint(1, 100, 50)

a = np.corrcoef(arr,arr2)
correlation = a[0, 1]

print(correlation)

0.12390284351442507


In [222]:
#Que 64
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


In [223]:
#Que 65
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)  # Median
p90 = np.percentile(arr, 90)

q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)

print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)
print("Q1 (25th Percentile):", q1)
print("Q3 (75th Percentile):", q3)

10th Percentile: 7.0
50th Percentile (Median): 55.5
90th Percentile: 81.5
Q1 (25th Percentile): 26.25
Q3 (75th Percentile): 74.5


##Search and Sort

In [224]:
#Que 66
arr = np.array([10, 25, 30, 45, 60, 15, 35])
index = np.where(arr == 30)[0]
if index.size > 0:
    print("Index of element 30:", index[0])
else:
    print("Element not found.")


Index of element 30: 2


In [227]:
#Que 67
rand = np.random.randint(1, 100, 10)
sort = np.sort(rand)
print("Sorted array:", sort)

Sorted array: [ 2  9 19 21 22 25 39 43 78 93]


In [229]:
#Que 68
greater_num = arr[arr > 20]
print(greater_num)

[25 30 45 60 35]


In [230]:
#Que 69
div_by_3 = arr[arr % 3 == 0]
print(div_by_3)

[30 45 60 15]


In [235]:
#Que 70
num = arr[(arr >= 20) & (arr <= 40)]
print(num)

[]


##Byte Order & Swapping

In [233]:
#Que 71
arr = np.array([1, 2, 3], dtype=np.int16)
byte_order = arr.dtype.byteorder
if byte_order == '=':
    byte_order = 'native (depends on system)'
elif byte_order == '<':
    byte_order = 'little-endian'
elif byte_order == '>':
    byte_order = 'big-endian'

print("Byte order:", byte_order)

Byte order: native (depends on system)


In [234]:
#Que 72
arr = np.array([1, 256, 65535], dtype=np.uint16)
arr.byteswap(inplace=True)
print(arr)

[  256     1 65535]
